name: Sync Ads_SukkaW Rule

on:
  schedule:
    # 北京时间 23:00 = UTC 15:00
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download upstream rule
        run: |
          curl -L -o Surge/Rules/Ads_SukkaW.list \
          https://raw.githubusercontent.com/Repcz/Tool/refs/heads/X/Surge/Rules/Ads_SukkaW.list

      - name: Remove specific rule
        run: |
          sed -i '/DOMAIN-SUFFIX,stat.y.qq.com/d' Surge/Rules/Ads_SukkaW.list

      - name: Commit if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Surge/Rules/Ads_SukkaW.list
          if ! git diff --staged --quiet; then
            git commit -m "Auto Sync Ads_SukkaW.list $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          fi
